# a = [1, 44, 4]

# print(a)


# if True:
#     print('hello')

# print(5/0)

# try:
#     a = int(input('введите цифру a: '))
#     b = int(input('введите цифру b: '))

#     print(a/b)
# except ZeroDivisionError:
#     print('На ноль делить нельзя!')
# except NameError:
#     print('Нету такого переменного!')

# except ValueError:
#     print('Веддите только цифры')

# while True:
#     try:
#         a = int(input('введите цифру a: '))
#         b = int(input('введите цифру b: '))    
#         print(a/b)
#     except ZeroDivisionError:
#         print('На ноль делить нельзя!')
#     except NameError:
#         print('Нету такого переменного!')
#     except ValueError:
#         print('Веддите только цифры')



# try:
#     a = int(input('введите цифру a: '))
#     b = int(input('введите цифру b: '))    
#     print(a/b)
# except(ZeroDivisionError, NameError, ValueError):
#     print('Поймал все ошибки')
# else:
#     print('Не поймал ни одну ошибку')
# finally:
#     print('FINNALY')


            
# try:
#     print('sdf'/5)
# except Exception as e:
#     print(f'Код вырубился из за ошибки {e}')


# s = {
#     'key':'value'
# }

# print(s['df'])





# len()
# input()
# print()
# range()
# int()
# str()
# tuple()
# type()


# Problem 1
# try:
#     a = stri
#     print(a)
# except NameError as i:
#     print(f'У вас вот такая ошибка {i}')

# try:
#     a = 55
#     b = "str"
#     print(a + b)
# except TypeError as b:
#     print(f'У вас вот такая ошибка {b}')

# try:
#     a = ['aktan', 'aslan', 'beka', 'akuu']
#     print(a[50])
# except IndexError as s:
#     print(f'У вас вот такая ошибка{s}')

# try:
#     dict_ = {'name': 'john', 'lastname': 'Snow', 12: 'age'}
#     for x in dict_.keys():
#         x + 'abc'
    
# print(dict)